AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function that forwards CloudWatch Alarms (via SNS) and
  EventBridge events to a Discord channel webhook.

# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------
Parameters:
  DiscordWebhookUrl:
    Type: String
    Description: Discord webhook URL for sending notifications.
    NoEcho: true

  AlarmTopicName:
    Type: String
    Default: CloudWatchAlarmsToDiscord
    Description: Name for the SNS topic that CloudWatch Alarms publish to.

  EventBridgeRulePrefix:
    Type: String
    Default: DiscordNotifier-
    Description: Prefix for EventBridge rule names.

# ---------------------------------------------------------------------------
# Resources
# ---------------------------------------------------------------------------
Resources:

  # -- SNS Topic for CloudWatch Alarms ---
  AlarmSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref AlarmTopicName

  # -- Sample Service Alarm (Lambda Errors) ---
  # Triggers the SNS topic when this Lambda function fails.
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-DiscordNotifier-Errors"
      AlarmDescription: "Alarms if the Discord Notifier Lambda function fails."
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
        - Name: FunctionName
          Value: !Ref DiscordNotifierFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmSnsTopic
      OKActions:
        - !Ref AlarmSnsTopic

  # -- Lambda Function ---
  DiscordNotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: discord-notifier
      Description: Forwards CloudWatch Alarms and EventBridge events to Discord.
      Runtime: python3.12
      Handler: handler.lambda_handler
      CodeUri: lambda_discord_notifier/
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
          LOG_LEVEL: INFO

      # Allow Lambda to write CloudWatch Logs.
      Policies:
        - AWSLambdaBasicExecutionRole

      # Event sources
      Events:
        # 1. SNS trigger (CloudWatch Alarms)
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref AlarmSnsTopic

        # 2. EventBridge rule – ECS Task Stopped
        EcsTaskStoppedRule:
          Type: EventBridgeRule
          Properties:
            RuleName: !Sub "${EventBridgeRulePrefix}TaskStopped"
            Pattern:
              source:
                - aws.ecs
              detail-type:
                - "ECS Task State Change"
              detail:
                lastStatus:
                  - STOPPED
                stoppedReason:
                  - exists: true

        # 3. EventBridge rule – ECS Service Action (Warn/Error)
        EcsServiceActionRule:
          Type: EventBridgeRule
          Properties:
            RuleName: !Sub "${EventBridgeRulePrefix}ServiceAction"
            Pattern:
              source:
                - aws.ecs
              detail-type:
                - "ECS Service Action"
              detail:
                eventType:
                  - WARN
                  - ERROR



# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------
Outputs:
  SnsTopicArn:
    Description: ARN of the SNS topic – point your CloudWatch Alarms here.
    Value: !Ref AlarmSnsTopic

  LambdaFunctionArn:
    Description: ARN of the Discord notifier Lambda function.
    Value: !GetAtt DiscordNotifierFunction.Arn
